### ISSUE TITLE
Update content-cli package on ML Workbench

### ISSUE THREAD

**Issue by jpsteege** [celonis/content-cli#131]
I know this issue is more related to the ML Workbench than to this package, but hopefully you can think along. 
On our ML Workbench which is up to date, we run content-cli version 1.3.0 from two years ago. We therefore miss some functionalities such as 'list'. Updating is not possible since NPM needs sudo permissions. 
Is there another way to update the content-cli package, or could a newer version be added to the next ML-workbench update?

Thanks in advance!

**Comment by promeris** [comment]
hey @jpsteege, please reach out to Celonis Customer Support on the issue and they should be able to help you.

**Comment by jpsteege** [comment]
Thanks, will do!
