### ISSUE TITLE
Appkey used for pushing package with importPackage doesn't get permissions to see the package

### ISSUE THREAD

**Issue by stebranchi** [celonis/content-cli#188]
Hi,

I encountered a problem using th apis. As said in the title if I import a Package using an api_key, then if I try to get all packages I will not be able to see the one just pushed.
Then I went into the ems and I saw that my api_key doesn't have permissions on the package pushed with it.

Step to reproduce:
-push a package into a space with ImportPackage
-findAllPackages will not show it to me

**Comment by promeris** [comment]
hey @stebranchi, we can't provide any solution here for any in-product behaviors. Would suggest to create a customer support ticket through [Celopeers](https://celopeers.com/) or other Customer Support channels. Thanks!
