### ISSUE TITLE
Authentication by Application key

### ISSUE THREAD

**Issue by kaztakata** [celonis/content-cli#68]
Currently content-cli can access to IBC via user API key only.
Looks like pycelonis.get_celonis method, is it possible to access via Application key too ?

In my environment, this works if I just changed code in profile.validator.js / http-client.service.js from `Bearer ${apiToken}` to `AppKey ${apiToken}`.

**Comment by promeris** [comment]
hey @kaztakata, thanks for reporting the issue. Currently we don't support authentication with an application key in content-cli. You are on the right track with the suggested changes, however replacing `Bearer ${apiToken}` with `AppKey ${apiToken}` in the mentioned files would then only support authentication with application key. The ideal state would be to support both user and application keys for authentication and there are a few changes needed to support it. The following list would summarize the needed changes. 

- Add option to provide application key in the `profile create` command.
- Add support for authenticating via `APPLICATION_TOKEN` environment variable.
- Add logic to conditionally switch between user and application key authentication based on the provided token.

I would say that this task is not complex to implement and would be a good first issue. We would highly appreciate your contribution by creating a pull request with these changes.

**Comment by kaztakata** [comment]
Dear @promeris 
I created pull request https://github.com/celonis/content-cli/pull/71 regarding this issue. It is my first pull request to OSS so please tell me if something incorrect manner.
