### ISSUE TITLE
Can't push widget with node version >12

### ISSUE THREAD

**Issue by lg0m3s** [celonis/content-cli#77]
Hi, I might be completely wrong but we've (me and @GencBlakqoriP9) spent like 30-40 minutes today debugging trying to figure out what was wrong when trying to push `semantic-layer` dist to `dev.dev.celonis.cloud`. I was getting `error:   Backend responded with status code [object Object]`and the backend on `cloud-package-manager` wasn't even processing the request. So we found out I was using node 14 (AFAIK you can only build with version >14) and can only push with version 12.

Would be nice to add a warning to the `content-cli widget push` that you need to use version 12 in order for it to work (if that's really true). That could save other peer's time in the future

Best regards!

**Comment by promeris** [comment]
hey @lg0m3s, can you please provide the node version you tried it with. The cli should support node v14 and I have been using these versions without problem: `node/14.4.0, node/14.16.0, node/14.17.6`. As for support of node v16, we are aware of an issue there and have a ticket to tackle it at some point.

**Comment by lg0m3s** [comment]
hey @promeris thanks for the quick response! I was trying with `v14.16.0` and was getting the error mentioned in the description. It has only worked successfully after doing `nvm use 12` and pushing again

**Comment by yaabed** [comment]
Node 16 should be supported now with v0.2 of content-cli.
