### ISSUE TITLE
Profile as file from interactive dialogue

### ISSUE THREAD

**Issue by MaStFAU** [celonis/content-cli#97]
It would be nice if the cli commands would work without the profile but by directly specifying API token and EMS URL.
Alternatively, it would be good if the create profile could be done with arguments rather than an interactive dialogue. Also, is it possible to specify a different directory for saving and loading the profiles?

**Comment by promeris** [comment]
We are sorry for the late response, as we haven't been getting notifications for the issues in the repository. Hope this is still relevant for you.

Any cli command will work without profile when providing `API_TOKEN` and `TEAM_URL` environment variables. Example:
```
API_TOKEN=123 TEAM_URL https://my-team.eu-1.celonis.cloud/ content-cli list packages
```
As for creating profiles with arguments or specifying a different directory for saving/loading profiles, we don't plan on supporting these at the moment, however we would highly appreciate a contribution on providing these functionalities.
